// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/posts.tsx";
import * as $5 from "./routes/signin.tsx";
import * as $6 from "./routes/signup.tsx";
import * as $$0 from "./islands/NavSetting.tsx";
import * as $$1 from "./islands/SigninForm.tsx";
import * as $$2 from "./islands/SignupForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/posts.tsx": $4,
    "./routes/signin.tsx": $5,
    "./routes/signup.tsx": $6,
  },
  islands: {
    "./islands/NavSetting.tsx": $$0,
    "./islands/SigninForm.tsx": $$1,
    "./islands/SignupForm.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
