// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.ts";
import * as $4 from "./routes/posts.tsx";
import * as $5 from "./routes/posts/[id].tsx";
import * as $6 from "./routes/posts/[id]/comment.ts";
import * as $7 from "./routes/posts/[id]/comment/[commentId].ts";
import * as $8 from "./routes/posts/[id]/edit.tsx";
import * as $9 from "./routes/posts/[id]/remove.ts";
import * as $10 from "./routes/posts/create.tsx";
import * as $11 from "./routes/signin.tsx";
import * as $12 from "./routes/signout.ts";
import * as $13 from "./routes/signup.tsx";
import * as $$0 from "./islands/Modal.tsx";
import * as $$1 from "./islands/SigninForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.ts": $3,
    "./routes/posts.tsx": $4,
    "./routes/posts/[id].tsx": $5,
    "./routes/posts/[id]/comment.ts": $6,
    "./routes/posts/[id]/comment/[commentId].ts": $7,
    "./routes/posts/[id]/edit.tsx": $8,
    "./routes/posts/[id]/remove.ts": $9,
    "./routes/posts/create.tsx": $10,
    "./routes/signin.tsx": $11,
    "./routes/signout.ts": $12,
    "./routes/signup.tsx": $13,
  },
  islands: {
    "./islands/Modal.tsx": $$0,
    "./islands/SigninForm.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
